version: 2

multi-ecosystem-groups:
  deps:
    schedule:
      interval: weekly

updates:
  - package-ecosystem: github-actions
    directory: /
    patterns: ["*"]
    multi-ecosystem-group: deps
  - package-ecosystem: docker
    directory: /docker
    patterns: ["*"]
    multi-ecosystem-group: deps
  - package-ecosystem: docker
    directory: /.devcontainer
    patterns: ["*"]
    multi-ecosystem-group: deps
  - package-ecosystem: devcontainers
    directory: /
    patterns: ["*"]
    multi-ecosystem-group: deps
  - package-ecosystem: pip
    directory: /.devcontainer
    patterns: ["*"]
    multi-ecosystem-group: deps
  - package-ecosystem: pre-commit
    directory: /
    patterns: ["*"]
    multi-ecosystem-group: deps
